export const STUDY_NOTE_VISIBILITY = {
  TEACHER_ONLY: 'TEACHER_ONLY',
  SPECIFIC_STUDENTS_ONLY: 'SPECIFIC_STUDENTS_ONLY',
  SPECIFIC_STUDENTS_AND_PARENTS: 'SPECIFIC_STUDENTS_AND_PARENTS',
  STUDY_ROOM_STUDENTS_ONLY: 'STUDY_ROOM_STUDENTS_ONLY',
  STUDY_ROOM_STUDENTS_AND_PARENTS: 'STUDY_ROOM_STUDENTS_AND_PARENTS',
  PUBLIC: 'PUBLIC',
} as const;
